from pathlib import Path

path=Path('index.html')
text=path.read_text(encoding='utf-8')

repls=[
('''        <button class="btn" data-tool="brush">Brush</button>\n        <button class="btn" data-tool="pan">Pan</button>''','''        <button class="btn" data-tool="brush">Brush</button>\n        <button class="btn" data-tool="eraser">Eraser</button>\n        <button class="btn" data-tool="pan">Pan</button>''','eraser tool button'),
('''      <p class="help">Choose a brush style, then adjust size, opacity and texture. Freehand and gradient fill colour a closed area you trace. Draw across edges to wrap. Two fingers zoom and move.</p>''','''      <p class="help">Choose a brush style, then adjust size, opacity and texture. Eraser removes pixels from the active unlocked layer and reveals layers underneath. Freehand and gradient fill colour a closed area you trace. Draw across edges to wrap. Two fingers zoom and move.</p>''','eraser help'),
('''  function layerArtworkCount(id){return state.items.filter(item=>item.layerId===id).length+state.marks.filter(mark=>mark.layerId===id).length;}''','''  function layerArtworkCount(id){return state.items.filter(item=>item.layerId===id).length+state.marks.filter(mark=>mark.layerId===id&&mark.type!=="eraser").length;}''','layer count ignores eraser actions'),
('''  function drawMark(c,m,alphaMultiplier=1){\n    const pts=m.points;if(!pts.length)return;\n    const opacity=clamp(Number(m.opacity??1),.05,1)*clamp(Number(alphaMultiplier??1),0,1),style=m.brushStyle||"ink";\n    c.save();c.strokeStyle=m.color;c.fillStyle=m.color;c.lineWidth=m.width;\n    c.lineCap="round";c.lineJoin="round";c.globalAlpha=opacity;''','''  function drawMark(c,m,alphaMultiplier=1){\n    const pts=m.points;if(!pts.length)return;\n    const opacity=clamp(Number(m.opacity??1),.05,1)*clamp(Number(alphaMultiplier??1),0,1),style=m.brushStyle||"ink";\n    c.save();c.strokeStyle=m.color;c.fillStyle=m.color;c.lineWidth=m.width;\n    c.lineCap="round";c.lineJoin="round";c.globalAlpha=opacity;\n    if(m.type==="eraser"){\n      c.globalCompositeOperation="destination-out";c.globalAlpha=1;c.lineWidth=m.width;\n      c.beginPath();c.moveTo(pts[0].x,pts[0].y);if(pts.length===1)c.lineTo(pts[0].x+.01,pts[0].y+.01);else for(let i=1;i<pts.length;i++)c.lineTo(pts[i].x,pts[i].y);c.stroke();c.restore();return;\n    }''','drawMark eraser composite'),
('''  function makeTileCanvas(W,H,baseW=W,baseH=H,style=projectRepeatStyle(),forExport=false){\n    const out=document.createElement("canvas"); out.width=W; out.height=H;\n    const c=out.getContext("2d");\n    if(!$("transparent").checked){ c.fillStyle=$("bg").value; c.fillRect(0,0,W,H); }\n\n    // Artwork is authored against a square 900-unit tile; export stays square.\n    const sx=baseW/TILE, sy=baseH/TILE;\n    const uniform=Math.sqrt(sx*sy);\n\n    const mapped=state.items.map(it=>({\n      ...it,\n      x:it.x*sx, y:it.y*sy,\n      scale:it.scale*uniform\n    }));\n    const basis=repeatBasis(baseW,baseH,style);\n    for(const layer of state.layers){\n      if(!layerIsRenderable(layer,forExport))continue;\n      for(const item of mapped){\n        if(layerForArtwork(item,BASE_LAYER_IDS.motifs)?.id===layer.id)drawWrapped(c,item,W,H,false,basis,layer.opacity);\n      }\n      drawMarksWrapped(c,W,H,baseW,baseH,style,layer.id,layer.opacity,forExport);\n    }\n    return out;\n  }''','''  function makeTileCanvas(W,H,baseW=W,baseH=H,style=projectRepeatStyle(),forExport=false){\n    const out=document.createElement("canvas"); out.width=W; out.height=H;\n    const c=out.getContext("2d");\n    if(!$("transparent").checked){ c.fillStyle=$("bg").value; c.fillRect(0,0,W,H); }\n\n    // Each layer renders into its own transparent surface so destination-out erasing\n    // removes only that layer and reveals lower layers/background correctly.\n    const sx=baseW/TILE, sy=baseH/TILE;\n    const uniform=Math.sqrt(sx*sy);\n    const mapped=state.items.map(it=>({...it,x:it.x*sx,y:it.y*sy,scale:it.scale*uniform}));\n    const basis=repeatBasis(baseW,baseH,style);\n    for(const layer of state.layers){\n      if(!layerIsRenderable(layer,forExport))continue;\n      const surface=document.createElement("canvas");surface.width=W;surface.height=H;const lc=surface.getContext("2d");\n      for(const item of mapped){\n        if(layerForArtwork(item,BASE_LAYER_IDS.motifs)?.id===layer.id)drawWrapped(lc,item,W,H,false,basis,1);\n      }\n      drawMarksWrapped(lc,W,H,baseW,baseH,style,layer.id,1,forExport);\n      c.save();c.globalAlpha=layer.opacity;c.drawImage(surface,0,0);c.restore();\n    }\n    return out;\n  }''','layer-isolated canvas rendering'),
('''      for(let idx=state.marks.length-1;idx>=0;idx--){const mark=state.marks[idx];if(layerForArtwork(mark,BASE_LAYER_IDS.drawing)?.id===layer.id&&markHitTest(mark,x,y))return {kind:"mark",artwork:mark};}''','''      for(let idx=state.marks.length-1;idx>=0;idx--){const mark=state.marks[idx];if(mark.type!=="eraser"&&layerForArtwork(mark,BASE_LAYER_IDS.drawing)?.id===layer.id&&markHitTest(mark,x,y))return {kind:"mark",artwork:mark};}''','eraser nonselectable'),
('''      if(m.type==="brush"||m.type==="freefill"||m.type==="gradient"){''','''      if(m.type==="brush"||m.type==="eraser"||m.type==="freefill"||m.type==="gradient"){''','eraser freehand points'),
('''    const mark={id:state.nextId++,layerId:drawLayer.id,type:state.tool,color:$("ink").value,width:Math.max(.45,parseInt($("brushSize").value,10)*TILE/4000),fill:$("shapeFill").checked,opacity:(parseInt($("inkOpacity").value,10)||100)/100,texture:(parseInt($("textureAmount").value,10)||0)/100,brushStyle:$("brushStyle").value,stampShape:$("stampShape").value,gradientType:$("gradientType").value,gradientDirection:$("gradientDirection").value,endColor:$("gradientEnd").value,points:[markStart]};''','''    const mark={id:state.nextId++,layerId:drawLayer.id,type:state.tool,color:$("ink").value,width:Math.max(.45,parseInt($("brushSize").value,10)*TILE/4000),fill:$("shapeFill").checked,opacity:state.tool==="eraser"?1:(parseInt($("inkOpacity").value,10)||100)/100,texture:(parseInt($("textureAmount").value,10)||0)/100,brushStyle:$("brushStyle").value,stampShape:$("stampShape").value,gradientType:$("gradientType").value,gradientDirection:$("gradientDirection").value,endColor:$("gradientEnd").value,points:[markStart]};''','eraser authored as full-strength mark'),
('''    const returnTool=state.previousTool&&state.previousTool!=="eyedropper"?state.previousTool:"select";''','''    const returnTool=state.previousTool&&state.previousTool!=="eyedropper"?state.previousTool:"select";''','eyedropper anchor'),
('''<meta name="app-version" content="1.2.0-alpha.5.1">''','''<meta name="app-version" content="1.2.0-alpha.5.2">''','version')
]

for old,new,label in repls:
    count=text.count(old)
    if count!=1:
        raise SystemExit(f'guard failed for {label}: expected 1 match, found {count}')
    text=text.replace(old,new,1)

# SVG needs per-layer masking for eraser marks while preserving vector artwork.
text=text.replace('''    for(const layer of state.layers){\n      if(!layerIsRenderable(layer,true))continue;\n      for(const srcItem of state.items){''','''    let maskIndex=0;\n    for(const layer of state.layers){\n      if(!layerIsRenderable(layer,true))continue;\n      let layerBody="",layerErase="";\n      for(const srcItem of state.items){''',1)
text=text.replace('''        body+=`<use href="#${assetRef}" xlink:href="#${assetRef}" x="${-iw/2}" y="${-ih/2}" width="${iw}" height="${ih}" opacity="${item.opacity*layer.opacity}" transform="translate(${x} ${y}) rotate(${deg})"/>`;''','''        layerBody+=`<use href="#${assetRef}" xlink:href="#${assetRef}" x="${-iw/2}" y="${-ih/2}" width="${iw}" height="${ih}" opacity="${item.opacity*layer.opacity}" transform="translate(${x} ${y}) rotate(${deg})"/>`;''',1)

# Insert eraser style selection and route generated elements into mask or visible layer body.
old='''      let style;\n      if(m.type==="gradient"){'''
new='''      let style;\n      if(m.type==="eraser")style=`stroke="#000" stroke-width="${m.width}" stroke-linecap="round" stroke-linejoin="round" fill="none" opacity="1"`;\n      else if(m.type==="gradient"){'''
if text.count(old)!=1: raise SystemExit('guard failed svg style anchor')
text=text.replace(old,new,1)

text=text.replace('''          for(const copy of copies)body+=`<g transform="scale(${sx} ${sy}) translate(${copy.x} ${copy.y})"><g transform="${transform}" ${style}>${shape}</g></g>`;''','''          for(const copy of copies){const node=`<g transform="scale(${sx} ${sy}) translate(${copy.x} ${copy.y})"><g transform="${transform}" ${style}>${shape}</g></g>`;if(m.type==="eraser")layerErase+=node;else layerBody+=node;}''',1)
text=text.replace('''          for(const copy of copies)body+=`<g transform="scale(${sx} ${sy}) translate(${copy.x} ${copy.y})"><g transform="${transform}"><g transform="${markTransform}" ${style}>${shape}</g></g></g>`;''','''          for(const copy of copies){const node=`<g transform="scale(${sx} ${sy}) translate(${copy.x} ${copy.y})"><g transform="${transform}"><g transform="${markTransform}" ${style}>${shape}</g></g></g>`;if(m.type==="eraser")layerErase+=node;else layerBody+=node;}''',1)

# Close each layer into a vector mask when it contains eraser strokes.
old='''      }\n    }\n    const svg=`<?xml version="1.0" encoding="UTF-8"?>'''
new='''      }\n      if(layerErase){const maskId=`pf-erase-${++maskIndex}`;gradientDefs+=`<mask id="${maskId}" maskUnits="userSpaceOnUse" x="0" y="0" width="${W}" height="${H}" style="mask-type:luminance"><rect width="${W}" height="${H}" fill="#fff"/>${layerErase}</mask>`;body+=`<g mask="url(#${maskId})">${layerBody}</g>`;}else body+=layerBody;\n    }\n    const svg=`<?xml version="1.0" encoding="UTF-8"?>'''
if text.count(old)!=1: raise SystemExit('guard failed svg layer close')
text=text.replace(old,new,1)

# Exclude eraser from selected-panel type and quality-visible mark test semantics is naturally harmless.
path.write_text(text,encoding='utf-8')
print('Applied guarded real eraser alpha.5.2 patch')
