from pathlib import Path

path = Path('index.html')
text = path.read_text(encoding='utf-8')


def replace_once(old, new, label):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'guard failed for {label}: expected 1 match, found {count}')
    text = text.replace(old, new, 1)


replace_once('<meta name="app-version" content="1.2.0-alpha.5.2">', '<meta name="app-version" content="1.2.0-alpha.6.0">', 'version')
replace_once('Arrange artwork into seamless repeats. Draw, place motifs, preview straight, half-drop and brick layouts, then export PNG, SVG or an editable project.', 'Create seamless repeat patterns or standalone doodles. Draw, place motifs and export reusable PNG, SVG or editable project files.', 'header description')
replace_once('Jump straight into a practice tile, or set up a print project with its name, customer, colourway and repeat layout.', 'Jump straight into a practice tile, or create a seamless Pattern Project or standalone Doodle Project.', 'setup intro')
replace_once('<p class="setupDivider"><span>Or create a print project</span></p>\n      <form id="projectSetupForm">\n        <div class="field"><label for="projectTitleInput">Project name</label>', '<p class="setupDivider"><span>Or create a project</span></p>\n      <form id="projectSetupForm">\n        <div class="field"><label for="projectTypeInput">Project type</label><select id="projectTypeInput"><option value="pattern">Pattern Project · seamless repeat</option><option value="doodle">Doodle Project · standalone artwork</option></select></div>\n        <div class="field"><label for="projectTitleInput">Project name</label>', 'project type setup')
replace_once('<div class="field"><label for="projectRepeatStyle">Repeat style</label><select id="projectRepeatStyle"><option value="straight">Straight repeat · square grid</option><option value="half-drop">Half-drop · rows shift sideways</option><option value="brick">Brick · columns shift down</option></select></div>\n        <p class="repeatLockNote">Repeat style is locked when the project is created. Half-drop exports a 4000 × 8000 px repeat swatch; brick exports 8000 × 4000 px. Straight repeat stays 4000 × 4000 px. All are tagged 300 DPI.</p>', '<div id="projectRepeatSetup"><div class="field"><label for="projectRepeatStyle">Repeat style</label><select id="projectRepeatStyle"><option value="straight">Straight repeat · square grid</option><option value="half-drop">Half-drop · rows shift sideways</option><option value="brick">Brick · columns shift down</option></select></div>\n        <p class="repeatLockNote">Repeat style is locked when the project is created. Half-drop exports a 4000 × 8000 px repeat swatch; brick exports 8000 × 4000 px. Straight repeat stays 4000 × 4000 px. All are tagged 300 DPI.</p></div>', 'repeat setup wrapper')
replace_once('<button id="createProject" class="btn primary full" type="submit">Create print project</button>', '<button id="createProject" class="btn primary full" type="submit">Create pattern project</button>', 'create project label')
replace_once('<details class="advancedDisclosure">\n      <summary>Optional image scatter</summary>', '<details id="patternScatterDisclosure" class="advancedDisclosure">\n      <summary>Optional image scatter</summary>', 'scatter id')
replace_once('<span class="stageDescription">4000 px master tile · seamless repeat preview</span>', '<span id="stageDescription" class="stageDescription">4000 px master tile · seamless repeat preview</span>', 'stage description id')
replace_once('<div class="stageControls repeatControls"><label for="neighborOpacity"', '<div id="repeatControls" class="stageControls repeatControls"><label for="neighborOpacity"', 'repeat controls id')
replace_once('<h3>Live repeat preview</h3>\n      <div id="preview" class="previewBox"></div>\n      <div class="field" style="margin-top:8px">', '<h3 id="repeatPreviewHeading">Live repeat preview</h3>\n      <div id="preview" class="previewBox"></div>\n      <div id="previewScaleField" class="field" style="margin-top:8px">', 'preview ids')
replace_once('<p class="exportGroupTitle">Pattern files</p>', '<p id="exportFilesTitle" class="exportGroupTitle">Pattern files</p>', 'export title id')
replace_once('<button id="exportPng" class="btn primary">Export pattern as PNG</button>\n        <button id="exportSvg" class="btn">Export pattern as SVG</button>', '<button id="exportPng" class="btn primary">Export pattern as PNG</button>\n        <button id="exportSvg" class="btn">Export pattern as SVG</button>', 'export buttons anchor')
replace_once('<p class="help">\n        PNG and SVG exports use the repeat swatch dimensions shown at left. The base drawing tile is 4000 × 4000 px; half-drop and brick swatches are rectangular.\n        SVG itself is resolution-independent; raster artwork inside an SVG remains raster.\n      </p>', '<p id="exportDimensionsHelp" class="help">\n        PNG and SVG exports use the repeat swatch dimensions shown at left. The base drawing tile is 4000 × 4000 px; half-drop and brick swatches are rectangular.\n        SVG itself is resolution-independent; raster artwork inside an SVG remains raster.\n      </p>', 'export dimensions id')
replace_once('Choose <strong>Start practice mode</strong> or create a named print project.', 'Choose <strong>Start practice mode</strong> or create a named Pattern Project or Doodle Project.', 'guide start')
replace_once('Use Preview repeat to check how your tile looks when repeated. Projects use straight, half-drop or brick repeat layouts. Export PNG for a raster image or SVG for a vector document; imported raster images remain raster inside SVG.', 'Pattern Projects use Preview repeat with straight, half-drop or brick layouts. Doodle Projects use one transparent standalone canvas with no automatic edge wrapping. Export PNG for reusable raster artwork or SVG for a vector document; imported raster images remain raster inside SVG.', 'guide preview')

replace_once('  function projectRepeatStyle(){return ["half-drop","brick"].includes(state.project?.repeatStyle)?state.project.repeatStyle:"straight";}', '  function projectType(){return state.project?.projectType==="doodle"?"doodle":"pattern";}\n  function isDoodleProject(){return projectType()==="doodle";}\n  function projectRepeatStyle(){if(isDoodleProject())return "straight";return ["half-drop","brick"].includes(state.project?.repeatStyle)?state.project.repeatStyle:"straight";}', 'project type helpers')

lattice_anchor = '''  function latticeCopiesForBounds(minX,maxX,minY,maxY,clipW,clipH,basis){\n    const corners=[[-maxX,-maxY],[clipW-minX,-maxY],[-maxX,clipH-minY],[clipW-minX,clipH-minY]].map(([x,y])=>latticeCoordinates(x,y,basis));\n    const ks=corners.map(p=>p.k),ns=corners.map(p=>p.n);\n    const k0=Math.floor(Math.min(...ks))-1,k1=Math.ceil(Math.max(...ks))+1;\n    const n0=Math.floor(Math.min(...ns))-1,n1=Math.ceil(Math.max(...ns))+1;\n    const copies=[];\n    for(let n=n0;n<=n1;n++)for(let k=k0;k<=k1;k++){\n      const x=k*basis[0].x+n*basis[1].x,y=k*basis[0].y+n*basis[1].y;\n      if(maxX+x>=0&&minX+x<=clipW&&maxY+y>=0&&minY+y<=clipH)copies.push({k,n,x,y});\n    }\n    return copies;\n  }'''
lattice_new = lattice_anchor + '''\n  function artworkCopiesForBounds(minX,maxX,minY,maxY,clipW,clipH,basis){\n    if(isDoodleProject())return maxX>=0&&minX<=clipW&&maxY>=0&&minY<=clipH?[{k:0,n:0,x:0,y:0}]:[];\n    return latticeCopiesForBounds(minX,maxX,minY,maxY,clipW,clipH,basis);\n  }'''
replace_once(lattice_anchor, lattice_new, 'standalone copy helper')

replace_once('  function nearestLatticeDelta(x,y,cx,cy){\n    const basis=repeatBasis(),coeff=latticeCoordinates(x-cx,y-cy,basis),k0=Math.round(coeff.k),n0=Math.round(coeff.n);', '  function nearestLatticeDelta(x,y,cx,cy){\n    if(isDoodleProject()){const dx=x-cx,dy=y-cy;return {x:dx,y:dy,distance:dx*dx+dy*dy};}\n    const basis=repeatBasis(),coeff=latticeCoordinates(x-cx,y-cy,basis),k0=Math.round(coeff.k),n0=Math.round(coeff.n);', 'doodle direct delta')
replace_once('  function canonicalPoint(x,y){\n    const style=projectRepeatStyle();', '  function canonicalPoint(x,y){\n    if(isDoodleProject())return {x,y};\n    const style=projectRepeatStyle();', 'doodle canonical point')
replace_once('    const copies=latticeCopiesForBounds(item.x-halfW,item.x+halfW,item.y-halfH,item.y+halfH,W,H,basis);', '    const copies=artworkCopiesForBounds(item.x-halfW,item.x+halfW,item.y-halfH,item.y+halfH,W,H,basis);', 'doodle item canvas copies')
replace_once('    const repeatReach=state.focusMode&&!state.focusRepeatPreview?0:2;', '    const repeatReach=isDoodleProject()?0:(state.focusMode&&!state.focusRepeatPreview?0:2);', 'editor repeat reach')
replace_once('  function normaliseMarkTranslation(m){\n    const b=markGeometryBounds(m),t=markTransformValues(m),centre={x:b.cx+t.x,y:b.cy+t.y},canonical=canonicalPoint(centre.x,centre.y);', '  function normaliseMarkTranslation(m){\n    if(isDoodleProject())return;\n    const b=markGeometryBounds(m),t=markTransformValues(m),centre={x:b.cx+t.x,y:b.cy+t.y},canonical=canonicalPoint(centre.x,centre.y);', 'doodle mark translation')
replace_once('          const copies=latticeCopiesForBounds(minX,maxX,minY,maxY,clipW,clipH,basis);', '          const copies=artworkCopiesForBounds(minX,maxX,minY,maxY,clipW,clipH,basis);', 'doodle mark canvas copies')
replace_once('          const bounds=markTransformedBounds(m,mirrorX,mirrorY,angle),copies=latticeCopiesForBounds(bounds.minX,bounds.maxX,bounds.minY,bounds.maxY,clipW,clipH,basis);', '          const bounds=markTransformedBounds(m,mirrorX,mirrorY,angle),copies=artworkCopiesForBounds(bounds.minX,bounds.maxX,bounds.minY,bounds.maxY,clipW,clipH,basis);', 'doodle transformed mark canvas copies')
replace_once('  function generate(){\n    if(state.assets.length===0){ setStatus("Add at least one drawing first."); return; }', '  function generate(){\n    if(isDoodleProject()){setStatus("Image scatter is available in Pattern Projects. Doodle Projects keep one standalone canvas.");return;}\n    if(state.assets.length===0){ setStatus("Add at least one drawing first."); return; }', 'doodle scatter guard')
replace_once('      item.x=((snapped.x%TILE)+TILE)%TILE;\n      item.y=((snapped.y%TILE)+TILE)%TILE;', '      item.x=isDoodleProject()?snapped.x:((snapped.x%TILE)+TILE)%TILE;\n      item.y=isDoodleProject()?snapped.y:((snapped.y%TILE)+TILE)%TILE;', 'doodle item drag')
replace_once('      const copies=latticeCopiesForBounds(item.x-halfW,item.x+halfW,item.y-halfH,item.y+halfH,W,H,itemBasis);', '      const copies=artworkCopiesForBounds(item.x-halfW,item.x+halfW,item.y-halfH,item.y+halfH,W,H,itemBasis);', 'doodle item svg copies')
replace_once('          const copies=latticeCopiesForBounds(minX,maxX,minY,maxY,clipW,clipH,markBasis);', '          const copies=artworkCopiesForBounds(minX,maxX,minY,maxY,clipW,clipH,markBasis);', 'doodle mark svg copies')
replace_once('          const bounds=markTransformedBounds(m,mirrorX,mirrorY,angle),copies=latticeCopiesForBounds(bounds.minX,bounds.maxX,bounds.minY,bounds.maxY,clipW,clipH,markBasis),markTransform=markSvgTransform(m);', '          const bounds=markTransformedBounds(m,mirrorX,mirrorY,angle),copies=artworkCopiesForBounds(bounds.minX,bounds.maxX,bounds.minY,bounds.maxY,clipW,clipH,markBasis),markTransform=markSvgTransform(m);', 'doodle transformed mark svg copies')

replace_once('  function safeName(){\n    const label=state.project?.title||$("seed").value||"pattern";\n    return label.replace(/[^a-z0-9_-]+/gi,"-").replace(/^-+|-+$/g,"")||"pattern";\n  }', '  function safeName(){\n    const label=state.project?.title||$("seed").value||"pattern";\n    return label.replace(/[^a-z0-9_-]+/gi,"-").replace(/^-+|-+$/g,"")||"pattern";\n  }\n  function exportFileStem(){return isDoodleProject()?"artwork":"seamless";}', 'export file stem')
replace_once('    downloadBlob(blob,`${safeName()}-seamless-${spec.dpi}dpi.png`);\n    setStatus(`Repeat PNG exported at ${spec.wPx} × ${spec.hPx}px with ${spec.dpi}-DPI metadata.`);', '    downloadBlob(blob,`${safeName()}-${exportFileStem()}-${spec.dpi}dpi.png`);\n    setStatus(isDoodleProject()?`Standalone PNG exported at ${spec.wPx} × ${spec.hPx}px with transparency and ${spec.dpi}-DPI metadata.`:`Repeat PNG exported at ${spec.wPx} × ${spec.hPx}px with ${spec.dpi}-DPI metadata.`);', 'png export naming')
replace_once('    downloadBlob(blob,`${safeName()}-seamless.svg`);\n    setStatus("Repeat SVG exported. Drawn marks remain vector; imported raster images stay raster.");', '    downloadBlob(blob,`${safeName()}-${exportFileStem()}.svg`);\n    setStatus(isDoodleProject()?"Standalone SVG exported. Drawn marks remain vector; imported raster images stay raster.":"Repeat SVG exported. Drawn marks remain vector; imported raster images stay raster.");', 'svg export naming')

badge_old = '''  function setProjectBadge(){\n    const p=state.project;\n    const styles={straight:"Straight", "half-drop":"Half-drop",brick:"Brick"};\n    $("projectNameDisplay").textContent=p?.isPractice?"Practice mode":p?`${p.title} · ${styles[p.repeatStyle]||"Straight"}`:"Tile editor";\n    $("projectNameDisplay").title=p?[p.title,p.customer,p.theme,p.variation,styles[p.repeatStyle]||"Straight repeat"].filter(Boolean).join(" · "):"";\n  }'''
badge_new = '''  function setProjectBadge(){\n    const p=state.project;\n    const styles={straight:"Straight", "half-drop":"Half-drop",brick:"Brick"},doodle=p?.projectType==="doodle";\n    $("projectNameDisplay").textContent=p?.isPractice?"Practice mode":p?`${p.title} · ${doodle?"Doodle":styles[p.repeatStyle]||"Straight"}`:"Tile editor";\n    $("projectNameDisplay").title=p?[p.title,p.customer,p.theme,p.variation,doodle?"Doodle Project":styles[p.repeatStyle]||"Straight repeat"].filter(Boolean).join(" · "):"";\n  }\n  function updateSetupProjectType(){\n    const doodle=$("projectTypeInput").value==="doodle";\n    $("projectRepeatSetup").hidden=doodle;\n    $("createProject").textContent=doodle?"Create doodle project":"Create pattern project";\n  }\n  function updateProjectModeUi(){\n    const doodle=isDoodleProject();\n    document.body.classList.toggle("doodle-project",doodle);\n    if(doodle){$("transparent").checked=true;state.focusRepeatPreview=false;$("repeatPreviewToggle").setAttribute("aria-pressed","false");$("repeatPreviewToggle").textContent="Preview repeat";}\n    $("transparent").disabled=doodle;$("bg").disabled=doodle;\n    $("patternScatterDisclosure").hidden=doodle;$("repeatControls").hidden=doodle;$("repeatPreviewToggle").hidden=doodle;\n    $("repeatPreviewHeading").hidden=doodle;$("preview").hidden=doodle;$("previewScaleField").hidden=doodle;\n    $("stageDescription").textContent=doodle?"4000 px standalone canvas · transparent background":"4000 px master tile · seamless repeat preview";\n    $("exportFilesTitle").textContent=doodle?"Artwork files":"Pattern files";\n    $("exportPng").textContent=doodle?"Export artwork as PNG":"Export pattern as PNG";\n    $("exportSvg").textContent=doodle?"Export artwork as SVG":"Export pattern as SVG";\n    $("exportDimensionsHelp").textContent=doodle?"Doodle exports are one transparent 4000 × 4000 px canvas. PNG carries 300-DPI metadata. SVG remains resolution-independent; raster artwork inside an SVG remains raster.":"PNG and SVG exports use the repeat swatch dimensions shown at left. The base drawing tile is 4000 × 4000 px; half-drop and brick swatches are rectangular. SVG itself is resolution-independent; raster artwork inside an SVG remains raster.";\n  }'''
replace_once(badge_old, badge_new, 'project mode UI')

replace_once('    $("projectTitleInput").value="";$("projectCustomerInput").value="";$("projectThemeInput").value="";$("projectVariationInput").value="";\n    $("projectRepeatStyle").value="straight";\n    $("projectRepeatStyle").disabled=!!state.project?.isPractice;\n    refreshLocalProjects();', '    $("projectTitleInput").value="";$("projectCustomerInput").value="";$("projectThemeInput").value="";$("projectVariationInput").value="";\n    $("projectTypeInput").value="pattern";$("projectTypeInput").disabled=!!state.project?.isPractice;\n    $("projectRepeatStyle").value="straight";\n    $("projectRepeatStyle").disabled=!!state.project?.isPractice;updateSetupProjectType();\n    refreshLocalProjects();', 'setup project type reset')
replace_once('      const detail=document.createElement("small");detail.textContent=p.isPractice?`Practice session · ${new Date(p.updatedAt||Date.now()).toLocaleString()}`:[p.customer,p.theme,p.variation,p.repeatStyle||"straight"].filter(Boolean).join(" · ");title.appendChild(detail);', '      const detail=document.createElement("small");detail.textContent=p.isPractice?`Practice session · ${new Date(p.updatedAt||Date.now()).toLocaleString()}`:[p.customer,p.theme,p.variation,p.projectType==="doodle"?"Doodle Project":p.repeatStyle||"straight"].filter(Boolean).join(" · ");title.appendChild(detail);', 'saved project detail')
replace_once('      const now=new Date().toISOString(),promotePractice=!!state.project?.isPractice;\n      state.project={id:newProjectId(),title,customer:$("projectCustomerInput").value.trim(),theme:$("projectThemeInput").value.trim(),variation:$("projectVariationInput").value.trim(),repeatStyle:promotePractice?"straight":$("projectRepeatStyle").value,createdAt:promotePractice?(state.project.createdAt||now):now,updatedAt:now};', '      const now=new Date().toISOString(),promotePractice=!!state.project?.isPractice,requestedType=promotePractice?"pattern":($("projectTypeInput").value==="doodle"?"doodle":"pattern");\n      state.project={id:newProjectId(),title,customer:$("projectCustomerInput").value.trim(),theme:$("projectThemeInput").value.trim(),variation:$("projectVariationInput").value.trim(),projectType:requestedType,repeatStyle:requestedType==="doodle"?"straight":(promotePractice?"straight":$("projectRepeatStyle").value),createdAt:promotePractice?(state.project.createdAt||now):now,updatedAt:now};', 'create project type')
replace_once('      $("projectSetupOverlay").hidden=true;setProjectBadge();rebuildAssetGrid();updatePixelReadout();updatePrintEligibility();scheduleAutosave();\n      setStatus(promotePractice?`Practice artwork saved as “${title}”. Its straight repeat is now a print project.`:`Project “${title}” saved on this device. Draw and colour your tile.`);', '      if(requestedType==="doodle")$("transparent").checked=true;\n      $("projectSetupOverlay").hidden=true;setProjectBadge();updateProjectModeUi();rebuildAssetGrid();updatePixelReadout();updatePrintEligibility();scheduleAutosave();\n      setStatus(promotePractice?`Practice artwork saved as “${title}”. Its straight repeat is now a Pattern Project.`:requestedType==="doodle"?`Doodle Project “${title}” saved. The 4000 px canvas is transparent and does not wrap at its edges.`:`Pattern Project “${title}” saved on this device. Draw and colour your seamless tile.`);', 'create project mode activation')
replace_once('    state.project={id:newProjectId(),title:"Practice mode",customer:"",theme:"",variation:"",repeatStyle:"straight",isPractice:true,createdAt:now,updatedAt:now};', '    state.project={id:newProjectId(),title:"Practice mode",customer:"",theme:"",variation:"",projectType:"pattern",repeatStyle:"straight",isPractice:true,createdAt:now,updatedAt:now};', 'practice project type')
replace_once('    $("projectSetupOverlay").hidden=true;setProjectBadge();rebuildAssetGrid();updatePixelReadout();updatePrintEligibility();', '    $("projectSetupOverlay").hidden=true;setProjectBadge();updateProjectModeUi();rebuildAssetGrid();updatePixelReadout();updatePrintEligibility();', 'practice mode UI')
replace_once('    state.project={id:options.asCopy?newProjectId():(typeof incoming.id==="string"&&incoming.id.startsWith("pf-project-")?incoming.id:newProjectId()),title:String(incoming.title||data.seed||"Untitled project").slice(0,80),customer:String(incoming.customer||"").slice(0,80),theme:String(incoming.theme||"").slice(0,60),variation:String(incoming.variation||"").slice(0,60),repeatStyle:["straight","half-drop","brick"].includes(incoming.repeatStyle)?incoming.repeatStyle:"straight",isPractice:options.asCopy?false:!!incoming.isPractice,createdAt:incoming.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};', '    state.project={id:options.asCopy?newProjectId():(typeof incoming.id==="string"&&incoming.id.startsWith("pf-project-")?incoming.id:newProjectId()),title:String(incoming.title||data.seed||"Untitled project").slice(0,80),customer:String(incoming.customer||"").slice(0,80),theme:String(incoming.theme||"").slice(0,60),variation:String(incoming.variation||"").slice(0,60),projectType:incoming.projectType==="doodle"?"doodle":"pattern",repeatStyle:incoming.projectType==="doodle"?"straight":(["straight","half-drop","brick"].includes(incoming.repeatStyle)?incoming.repeatStyle:"straight"),isPractice:options.asCopy?false:!!incoming.isPractice,createdAt:incoming.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};', 'restore project type')
replace_once('    $("bg").value=data.background||"#ffffff";$("transparent").checked=!!data.transparent;if(typeof data.seed==="string")$("seed").value=data.seed;const s=data.settings||{};', '    $("bg").value=data.background||"#ffffff";$("transparent").checked=isDoodleProject()?true:!!data.transparent;if(typeof data.seed==="string")$("seed").value=data.seed;const s=data.settings||{};', 'restore doodle transparency')
replace_once('    rebuildAssetGrid();renderAll();setProjectBadge();updatePixelReadout();updateSettingReadouts();updatePrintEligibility();saveAutosave();', '    updateProjectModeUi();rebuildAssetGrid();renderAll();setProjectBadge();updatePixelReadout();updateSettingReadouts();updatePrintEligibility();saveAutosave();', 'restore mode UI')

replace_once('        {name:`${base}-seamless-${png.spec.dpi}dpi.png`,blob:png.blob},\n        {name:`${base}-seamless.svg`,blob:renderSVGBlob()},', '        {name:`${base}-${exportFileStem()}-${png.spec.dpi}dpi.png`,blob:png.blob},\n        {name:`${base}-${exportFileStem()}.svg`,blob:renderSVGBlob()},', 'zip artwork names')
replace_once('      await shareOrDownloadZip(zip,`${base}-pattern-project.zip`);', '      await shareOrDownloadZip(zip,`${base}-${isDoodleProject()?"doodle":"pattern"}-project.zip`);', 'zip project name')

replace_once('  $("projectSetupForm").addEventListener("submit",createProjectFromSetup);', '  $("projectSetupForm").addEventListener("submit",createProjectFromSetup);\n  $("projectTypeInput").addEventListener("change",updateSetupProjectType);', 'project type listener')
replace_once('  $("repeatPreviewToggle").addEventListener("click",()=>{\n    state.focusRepeatPreview=!state.focusRepeatPreview;', '  $("repeatPreviewToggle").addEventListener("click",()=>{\n    if(isDoodleProject()){setStatus("Doodle Projects use one standalone canvas and do not have a repeat preview.");return;}\n    state.focusRepeatPreview=!state.focusRepeatPreview;', 'repeat preview doodle guard')

path.write_text(text, encoding='utf-8')
print('Applied Pattern Forge Doodle Mode foundation alpha.6.0')
