from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

def replace_once(old,new,label):
    count=s.count(old)
    if count!=1:
        raise SystemExit(f'{label}: expected 1 occurrence, found {count}')
    return s.replace(old,new,1)

s=replace_once('content="1.2.0-alpha.6.3"','content="1.2.0-alpha.6.4"','version')

old_css='''  .assetGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;max-height:225px;overflow:auto}\n  .asset{\n    position:relative;border:1px solid var(--line);border-radius:10px;background:#faf9f6;aspect-ratio:1;\n    display:flex;align-items:center;justify-content:center;overflow:hidden;padding:4px;cursor:pointer\n  }\n  .asset img{max-width:100%;max-height:100%;object-fit:contain}\n  .asset:hover{outline:2px solid rgba(44,95,84,.35)}\n  .asset span{position:absolute;left:4px;right:4px;bottom:3px;background:rgba(255,255,255,.82);font-size:.6rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;padding:2px 4px;border-radius:4px}'''
new_css='''  .assetGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;max-height:225px;overflow:auto}\n  .assetWrap{position:relative;aspect-ratio:1;min-width:0}\n  .asset{\n    position:relative;width:100%;height:100%;border:1px solid var(--line);border-radius:10px;background:#faf9f6;\n    display:flex;align-items:center;justify-content:center;overflow:hidden;padding:4px;cursor:pointer\n  }\n  .asset img{max-width:100%;max-height:100%;object-fit:contain}\n  .asset:hover{outline:2px solid rgba(44,95,84,.35)}\n  .asset span{position:absolute;left:4px;right:4px;bottom:3px;background:rgba(255,255,255,.82);font-size:.6rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;padding:2px 4px;border-radius:4px}\n  .assetRemove{position:absolute;z-index:3;top:4px;right:4px;width:28px;height:28px;border:1px solid rgba(138,46,46,.35);border-radius:999px;background:rgba(255,255,255,.94);color:var(--danger);font-weight:900;font-size:1rem;line-height:1;padding:0;box-shadow:0 2px 7px rgba(0,0,0,.12)}\n  .assetRemove:hover{background:#fff1ef;border-color:var(--danger)}'''
s=replace_once(old_css,new_css,'asset CSS')

s=replace_once('      const assetId="a"+(state.assets.length+1);','      const assetId=nextAssetId();','asset id allocation')

old_func='''  function rebuildAssetGrid(){\n    const g=$("assetGrid");\n    g.innerHTML="";\n    state.assets.forEach(a=>{\n      const d=document.createElement("button");\n      d.type="button"; d.className="asset"; d.title=`Add ${a.name}`;\n      const im=document.createElement("img"); im.src=a.src; im.alt="";\n      const sp=document.createElement("span"); sp.textContent=a.name;\n      d.append(im,sp);\n      d.addEventListener("click",()=>addAssetInstance(a));\n      g.appendChild(d);\n    });\n    rebuildFocusRecent();\n  }'''
new_func='''  function nextAssetId(){\n    const used=new Set(state.assets.map(asset=>String(asset.id)));\n    let max=0;\n    for(const id of used){const match=/^a(\\d+)$/i.exec(id);if(match)max=Math.max(max,Number(match[1])||0);}\n    let n=max+1;while(used.has(`a${n}`))n++;return `a${n}`;\n  }\n  function removeAssetFromLibrary(asset){\n    const placed=state.items.filter(item=>String(item.assetId)===String(asset.id));\n    if(placed.length){\n      const copies=`${placed.length} placed cop${placed.length===1?"y":"ies"}`;\n      if(!confirm(`Remove “${asset.name}” from the image library and remove ${copies} from this project?`))return;\n    }\n    state.items=state.items.filter(item=>String(item.assetId)!==String(asset.id));\n    if(placed.some(item=>item.id===state.selectedId))state.selectedId=null;\n    state.assets=state.assets.filter(candidate=>String(candidate.id)!==String(asset.id));\n    state.recentAssetIds=state.recentAssetIds.filter(id=>String(id)!==String(asset.id));\n    rebuildAssetGrid();\n    renderAll();\n    const removedCopies=placed.length?` and ${placed.length} placed cop${placed.length===1?"y":"ies"}`:"";\n    setStatus(`Removed “${asset.name}” from the image library${removedCopies}.`);\n  }\n  function rebuildAssetGrid(){\n    const g=$("assetGrid");\n    g.innerHTML="";\n    state.assets.forEach(a=>{\n      const wrap=document.createElement("div");wrap.className="assetWrap";\n      const d=document.createElement("button");\n      d.type="button";d.className="asset";d.title=`Add ${a.name}`;d.setAttribute("aria-label",`Add ${a.name}`);\n      const im=document.createElement("img");im.src=a.src;im.alt="";\n      const sp=document.createElement("span");sp.textContent=a.name;\n      d.append(im,sp);\n      d.addEventListener("click",()=>addAssetInstance(a));\n      const remove=document.createElement("button");\n      remove.type="button";remove.className="assetRemove";remove.textContent="×";remove.title=`Remove ${a.name} from image library`;remove.setAttribute("aria-label",`Remove ${a.name} from image library`);\n      remove.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();removeAssetFromLibrary(a);});\n      wrap.append(d,remove);\n      g.appendChild(wrap);\n    });\n    rebuildFocusRecent();\n  }'''
s=replace_once(old_func,new_func,'asset library rendering')

p.write_text(s,encoding='utf-8')
print('Applied alpha.6.4 image library removal')
