from pathlib import Path
p=Path('app/js/canvas-first-v2.js')
s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s: raise SystemExit(f'{label} anchor not found')
    s=s.replace(old,new,1)

rep('''        <button class="ux2-tool" data-ux2-tool="pan">${icon('pan')}<b>Pan</b></button>
      </nav>''','''        <button class="ux2-tool" data-ux2-tool="pan">${icon('pan')}<b>Pan</b></button>
        <button class="ux2-tool" data-ux2-action="image">${icon('image')}<b>Image</b></button>
        <button class="ux2-tool" data-ux2-tool="rect">${icon('shape')}<b>Shape</b></button>
      </nav>''','tool rail')
rep('''        <button class="ux2-dock" data-ux2-panel="colour"><span style="width:20px;height:20px;border-radius:50%;border:2px solid currentColor;background:#6f89a8"></span><b>Colour</b></button>
        <button class="ux2-dock" data-ux2-panel="layers"><span style="font-size:23px;line-height:1">≡</span><b>Layers</b></button>
        <button class="ux2-dock" data-ux2-panel="pattern"><span style="font-size:21px;line-height:1">▦</span><b>Pattern</b></button>''','''        <button class="ux2-dock" data-ux2-panel="colour">${icon('colour')}<b>Colour</b></button>
        <button class="ux2-dock" data-ux2-panel="layers">${icon('layers')}<b>Layers</b></button>
        <button class="ux2-dock" data-ux2-panel="pattern">${icon('repeat')}<b>Pattern</b></button>''','dock icons')
rep("const hints={select:'Select artwork to move, scale or rotate',brush:'Draw on the active layer',eraser:'Erase from the active layer',freefill:'Trace a closed area to fill',pan:'Move around the canvas'};","const hints={select:'Select artwork to move, scale or rotate',brush:'Draw on the active layer',eraser:'Erase from the active layer',freefill:'Trace a closed area to fill',gradient:'Trace a closed area for gradient fill',pan:'Move around the canvas',line:'Draw a straight line',rect:'Draw a rectangle',ellipse:'Draw an ellipse'};",'hints')
rep('''      context.innerHTML=`<div class="ux2-context-group"><span class="ux2-label">${tool==='eraser'?'Eraser':'Brush'}</span><select id="ux2BrushStyle"><option value="ink">Ink</option><option value="pencil">Pencil</option><option value="marker">Marker</option><option value="texture">Textured paint</option><option value="stamp">Stamp</option></select></div><div class="ux2-context-group"><label class="ux2-slider">Size <input id="ux2Size" type="range" min="2" max="400" value="${size}"><b id="ux2SizeOut">${size}</b></label><label class="ux2-slider">Opacity <input id="ux2Opacity" type="range" min="5" max="100" value="${opacity}"><b id="ux2OpacityOut">${opacity}%</b></label></div>`;''','''      context.innerHTML=`<div class="ux2-context-group"><span class="ux2-label">${tool==='eraser'?'Eraser':'Brush'}</span><select id="ux2BrushStyle"><option value="ink">Ink</option><option value="pencil">Pencil</option><option value="marker">Marker</option><option value="texture">Textured paint</option><option value="stamp">Stamp</option></select>${tool==='brush'?'<button class="ux2-chip" id="ux2BrushLibrary">Brush library</button>':''}</div><div class="ux2-context-group"><label class="ux2-slider">Size <input id="ux2Size" type="range" min="2" max="400" value="${size}"><b id="ux2SizeOut">${size}</b></label><label class="ux2-slider">Opacity <input id="ux2Opacity" type="range" min="5" max="100" value="${opacity}"><b id="ux2OpacityOut">${opacity}%</b></label></div>`;''','brush context')
rep('''      $('ux2Opacity').addEventListener('input',e=>{dispatchValue('inkOpacity',e.target.value);$('ux2OpacityOut').textContent=e.target.value+'%'});
    } else if(tool==='freefill'){''','''      $('ux2Opacity').addEventListener('input',e=>{dispatchValue('inkOpacity',e.target.value);$('ux2OpacityOut').textContent=e.target.value+'%'});
      if($('ux2BrushLibrary'))$('ux2BrushLibrary').addEventListener('click',()=>openPanel('brushes'));
    } else if(['line','rect','ellipse'].includes(tool)){
      const size=$('brushSize')?.value||20,filled=$('shapeFill')?.checked;
      context.innerHTML=`<div class="ux2-context-group"><span class="ux2-label">Shape</span><button class="ux2-chip ${tool==='line'?'active':''}" id="ux2Line">Line</button><button class="ux2-chip ${tool==='rect'?'active':''}" id="ux2Rect">Rectangle</button><button class="ux2-chip ${tool==='ellipse'?'active':''}" id="ux2Ellipse">Ellipse</button></div><div class="ux2-context-group"><label class="ux2-slider">Width <input id="ux2ShapeWidth" type="range" min="2" max="400" value="${size}"><b>${size}</b></label>${tool==='line'?'':`<label style="display:flex;align-items:center;gap:6px;font-size:11px"><input id="ux2ShapeFill" type="checkbox" ${filled?'checked':''}> Fill shape</label>`}<button class="ux2-chip" id="ux2ShapeColour">Colour</button></div>`;
      $('ux2Line').addEventListener('click',()=>setTool('line'));$('ux2Rect').addEventListener('click',()=>setTool('rect'));$('ux2Ellipse').addEventListener('click',()=>setTool('ellipse'));
      $('ux2ShapeWidth').addEventListener('input',e=>{dispatchValue('brushSize',e.target.value);renderContext(tool)});
      if($('ux2ShapeFill'))$('ux2ShapeFill').addEventListener('change',e=>dispatchChecked('shapeFill',e.target.checked));$('ux2ShapeColour').addEventListener('click',()=>openPanel('colour'));
    } else if(tool==='freefill'){''','shape context')
rep("document.querySelectorAll('[data-ux2-tool]').forEach(b=>b.classList.toggle('active',b.dataset.ux2Tool===tool));","const railTool=['line','rect','ellipse'].includes(tool)?'rect':tool;\n    document.querySelectorAll('[data-ux2-tool]').forEach(b=>b.classList.toggle('active',b.dataset.ux2Tool===railTool));",'shape rail state')
rep('''  function colourPanel(){''','''  function brushPanel(){
    const current=$('brushStyle')?.value||'ink';
    const styles=[['ink','Ink','Clean, solid line'],['pencil','Pencil','Lighter textured edge'],['marker','Marker','Broader translucent stroke'],['texture','Textured paint','Broken paint texture'],['stamp','Stamp','Repeated shape marks']];
    return `<div class="ux2-panel-block"><div class="ux2-panel-label">Brush library</div><div class="ux2-brush-list">${styles.map(([value,name,desc])=>`<button class="ux2-brush-card ${current===value?'active':''}" data-brush-style="${value}"><span class="ux2-brush-sample ${value}"></span><span><strong>${name}</strong><small>${desc}</small></span></button>`).join('')}</div></div>${current==='stamp'?`<div class="ux2-panel-block"><div class="ux2-panel-label">Stamp shape</div><div class="ux2-segment"><button data-stamp="leaf">Leaf</button><button data-stamp="star">Star</button><button data-stamp="dot">Dot</button></div></div>`:''}`;
  }

  function colourPanel(){''','brush panel function')
rep('''    return `<div class="ux2-panel-block"><div class="ux2-panel-label">Current colour</div><input id="ux2ColourInput" type="color" value="${colour}" style="width:100%;height:58px;border:1px solid #c7d0da;border-radius:12px;padding:4px;background:#fff"></div><div class="ux2-panel-block"><div class="ux2-panel-label">Current palette</div><div id="ux2PaletteSwatches" class="ux2-swatches"></div></div><div class="ux2-panel-block"><button class="ux2-btn" id="ux2Eyedropper" style="width:100%">Pick colour from canvas</button></div>`;''','''    const palettes=$('savedPaletteSelect')?[...$('savedPaletteSelect').options].map(o=>`<option value="${o.value}">${o.textContent}</option>`).join(''):'';
    return `<div class="ux2-panel-block"><div class="ux2-panel-label">Current colour</div><input id="ux2ColourInput" type="color" value="${colour}" style="width:100%;height:58px;border:1px solid #c7d0da;border-radius:12px;padding:4px;background:#fff"></div><div class="ux2-panel-block"><div class="ux2-panel-label">Current palette</div><div id="ux2PaletteSwatches" class="ux2-swatches"></div><button class="ux2-btn" id="ux2AddPaletteColour" style="width:100%;margin-top:9px">Add current colour</button></div><div class="ux2-panel-block"><div class="ux2-panel-label">Saved palettes</div><select id="ux2SavedPalette" style="width:100%;margin-bottom:8px">${palettes}</select><button class="ux2-btn" id="ux2SavePalette" style="width:100%">Save current palette</button></div><div class="ux2-panel-block"><button class="ux2-btn" id="ux2Eyedropper" style="width:100%">Pick colour from canvas</button></div>`;''','colour depth')
old_layer=s[s.index('  function layerPanel(){'):s.index('  function patternPanel(){')]
new_layer='''  function layerPanel(){
    const layers=[...document.querySelectorAll('#layerList .layerRow')];
    const rows=layers.map((row,i)=>`<button class="ux2-layer-row ${row.classList.contains('active')?'active':''}" data-layer-index="${i}"><span class="ux2-layer-thumb"></span><span><strong>${row.querySelector('.layerRowName')?.textContent||`Layer ${i+1}`}</strong><small>${row.querySelector('.layerRowMeta')?.textContent||'Artwork layer'}</small></span><span>›</span></button>`).join('')||'<p style="color:#687483;font-size:12px">Layers will appear here when a project is open.</p>';
    const name=String($('layerName')?.value||'');
    return `<div class="ux2-panel-block"><div class="ux2-panel-label">Artwork layers</div>${rows}<button class="ux2-btn" id="ux2AddLayer" style="width:100%;margin-top:6px">+ Add layer</button></div><div class="ux2-panel-block"><div class="ux2-panel-label">Selected layer</div><label class="ux2-field-label">Name<input id="ux2LayerName" type="text" value="${name.replace(/"/g,'&quot;')}"></label><label class="ux2-slider">Opacity <input id="ux2LayerOpacity" type="range" min="0" max="100" value="${$('layerOpacity')?.value||100}"></label><div class="ux2-check-grid"><label><input id="ux2LayerVisible" type="checkbox" ${$('layerVisible')?.checked?'checked':''}> Visible</label><label><input id="ux2LayerLocked" type="checkbox" ${$('layerLocked')?.checked?'checked':''}> Lock</label><label><input id="ux2LayerExport" type="checkbox" ${$('layerExport')?.checked?'checked':''}> Export</label></div><div class="ux2-segment" style="margin-top:9px"><button id="ux2LayerUp">Move up</button><button id="ux2LayerDown">Move down</button></div><div class="ux2-segment" style="margin-top:7px"><button id="ux2LayerDuplicate">Duplicate</button><button id="ux2LayerDelete">Delete</button></div></div>`;
  }
'''
s=s.replace(old_layer,new_layer,1)
old_pattern=s[s.index('  function patternPanel(){'):s.index('  function exportPanel(){')]
new_pattern='''  function patternPanel(){
    const doodle=document.body.classList.contains('doodle-project'),repeat=doodle?'Doodle':($('projectRepeatStyle')?.value||'straight').replace('-', ' ');
    if(doodle)return `<div class="ux2-panel-block"><div class="ux2-panel-label">Workspace</div><div class="ux2-repeat-card"><strong>Doodle</strong><span>Standalone transparent artwork. Repeat tools are intentionally hidden.</span></div></div>`;
    const grid=$('gridCount')?.value||16,sym=$('symmetry')?.value||'off',guide=$('constructionGuide')?.value||'off';
    return `<div class="ux2-panel-block"><div class="ux2-panel-label">Repeat</div><div class="ux2-repeat-card"><strong>${repeat}</strong><span>${$('pixelReadout')?.textContent||'4000 × 4000'} · 300 DPI metadata</span></div><button class="ux2-btn" id="ux2FullPreview" style="width:100%;margin-top:8px">Full repeat preview</button><button class="ux2-btn" id="ux2SeamInspect" style="width:100%;margin-top:7px">Inspect seams</button><label class="ux2-slider" style="margin-top:8px">Repeat visibility <input id="ux2Neighbour" type="range" min="15" max="100" value="${$('neighborOpacity')?.value||35}"></label><label class="ux2-check"><input id="ux2TileEdge" type="checkbox" ${$('showTileBorder')?.checked?'checked':''}> Show centre tile edge</label></div><div class="ux2-panel-block"><div class="ux2-panel-label">Construction</div><label class="ux2-field-label">Grid divisions<select id="ux2Grid"><option value="8">8 × 8</option><option value="10">10 × 10</option><option value="16">16 × 16</option><option value="20">20 × 20</option><option value="40">40 × 40</option></select></label><label class="ux2-check"><input id="ux2GridOn" type="checkbox" ${$('gridOn')?.checked?'checked':''}> Show grid</label><label class="ux2-field-label">Mirror while drawing<select id="ux2Symmetry"><option value="off">Off</option><option value="vertical">Vertical</option><option value="horizontal">Horizontal</option><option value="quadrant">Quadrant · 4 copies</option><option value="radial">8-way radial</option></select></label><label class="ux2-check"><input id="ux2SymmetryGuides" type="checkbox" ${$('symmetryGuides')?.checked?'checked':''}> Show mirror guides</label><label class="ux2-field-label">Guide<select id="ux2Guide"><option value="off">Off</option><option value="centre">Centre cross</option><option value="diagonals">Diagonals</option><option value="diamond">Diamond</option><option value="all">All guides</option></select></label><label class="ux2-check"><input id="ux2SnapOn" type="checkbox" ${$('snapOn')?.checked?'checked':''}> Smart snapping</label></div>`;
  }
'''
s=s.replace(old_pattern,new_pattern,1)
old_export=s[s.index('  function exportPanel(){'):s.index('\n\n  function openPanel(name){')]
new_export='''  function exportPanel(){
    const quality=$('quality')?.textContent?.trim()||'Add artwork to calculate print quality.',pixels=$('pixelReadout')?.textContent||'4000 × 4000';
    return `<div class="ux2-panel-block"><div class="ux2-panel-label">Export confidence</div><div class="ux2-repeat-card"><strong>${pixels}</strong><span>PNG carries 300 DPI metadata.</span></div><p class="ux2-info">${quality}</p></div><div class="ux2-panel-block"><div class="ux2-panel-label">Artwork</div><button class="ux2-btn primary" data-export-old="exportPng" style="width:100%;margin-bottom:7px">Export PNG · 300 DPI</button><button class="ux2-btn" data-export-old="exportSvg" style="width:100%">Export SVG</button></div><div class="ux2-panel-block"><div class="ux2-panel-label">Editable project</div><button class="ux2-btn" data-export-old="saveProject" style="width:100%;margin-bottom:7px">Save editable project</button><button class="ux2-btn" data-export-old="openProject" style="width:100%;margin-bottom:7px">Open project file</button><button class="ux2-btn" data-export-old="exportZip" style="width:100%">Download project bundle</button></div>`;
  }
'''
s=s.replace(old_export,new_export,1)
rep("$('ux2PaletteTitle').textContent=name==='colour'?'Colour':name==='layers'?'Layers':name==='pattern'?'Pattern':'Export';","$('ux2PaletteTitle').textContent=name==='colour'?'Colour':name==='layers'?'Layers':name==='pattern'?'Pattern':name==='brushes'?'Brush Library':'Export';",'panel title')
rep("body.innerHTML=name==='colour'?colourPanel():name==='layers'?layerPanel():name==='pattern'?patternPanel():exportPanel();","body.innerHTML=name==='colour'?colourPanel():name==='layers'?layerPanel():name==='pattern'?patternPanel():name==='brushes'?brushPanel():exportPanel();",'panel body')
rep("if(name==='colour'){$('ux2ColourInput').addEventListener('input',e=>dispatchValue('ink',e.target.value));$('ux2Eyedropper').addEventListener('click',()=>setTool('eyedropper'));populateSwatches()}","if(name==='colour'){$('ux2ColourInput').addEventListener('input',e=>dispatchValue('ink',e.target.value));$('ux2Eyedropper').addEventListener('click',()=>setTool('eyedropper'));$('ux2AddPaletteColour')?.addEventListener('click',()=>{clickOld('addPaletteColour');populateSwatches()});$('ux2SavePalette')?.addEventListener('click',()=>clickOld('savePalette'));if($('ux2SavedPalette')&&$('savedPaletteSelect')){$('ux2SavedPalette').value=$('savedPaletteSelect').value;$('ux2SavedPalette').addEventListener('change',e=>dispatchValue('savedPaletteSelect',e.target.value,'change'))}populateSwatches()}\n    if(name==='brushes'){document.querySelectorAll('[data-brush-style]').forEach(b=>b.addEventListener('click',()=>{dispatchValue('brushStyle',b.dataset.brushStyle,'change');setTool('brush');openPanel('brushes')}));document.querySelectorAll('[data-stamp]').forEach(b=>b.addEventListener('click',()=>dispatchValue('stampShape',b.dataset.stamp,'change')))}",'colour/brush events')
rep("$('ux2AddLayer').addEventListener('click',()=>{clickOld('layerAdd');openPanel('layers')});$('ux2LayerDuplicate').addEventListener('click',()=>{clickOld('layerDuplicate');openPanel('layers')});$('ux2LayerDelete').addEventListener('click',()=>{clickOld('layerDelete');openPanel('layers')});$('ux2LayerOpacity').addEventListener('input',e=>dispatchValue('layerOpacity',e.target.value));","$('ux2AddLayer').addEventListener('click',()=>{clickOld('layerAdd');openPanel('layers')});$('ux2LayerDuplicate').addEventListener('click',()=>{clickOld('layerDuplicate');openPanel('layers')});$('ux2LayerDelete').addEventListener('click',()=>{clickOld('layerDelete');openPanel('layers')});$('ux2LayerUp').addEventListener('click',()=>{clickOld('layerUp');openPanel('layers')});$('ux2LayerDown').addEventListener('click',()=>{clickOld('layerDown');openPanel('layers')});$('ux2LayerOpacity').addEventListener('input',e=>dispatchValue('layerOpacity',e.target.value));$('ux2LayerName').addEventListener('change',e=>dispatchValue('layerName',e.target.value,'change'));$('ux2LayerVisible').addEventListener('change',e=>dispatchChecked('layerVisible',e.target.checked));$('ux2LayerLocked').addEventListener('change',e=>dispatchChecked('layerLocked',e.target.checked));$('ux2LayerExport').addEventListener('change',e=>dispatchChecked('layerExport',e.target.checked));",'layer events')
old_pattern_events="if(name==='pattern'&&!document.body.classList.contains('doodle-project')){$('ux2FullPreview')?.addEventListener('click',()=>clickOld('repeatPreviewToggle'));$('ux2Neighbour')?.addEventListener('input',e=>dispatchValue('neighborOpacity',e.target.value));$('ux2TileEdge')?.addEventListener('change',e=>dispatchChecked('showTileBorder',e.target.checked))}"
new_pattern_events="if(name==='pattern'&&!document.body.classList.contains('doodle-project')){$('ux2FullPreview')?.addEventListener('click',()=>clickOld('repeatPreviewToggle'));$('ux2SeamInspect')?.addEventListener('click',()=>{dispatchValue('neighborOpacity','100');dispatchChecked('showTileBorder',true);clickOld('fit');const st=$('status');if(st)st.textContent='Seam inspection: repeat neighbours are at full visibility and the centre tile edge is marked.';openPanel('pattern')});$('ux2Neighbour')?.addEventListener('input',e=>dispatchValue('neighborOpacity',e.target.value));$('ux2TileEdge')?.addEventListener('change',e=>dispatchChecked('showTileBorder',e.target.checked));$('ux2Grid').value=String($('gridCount')?.value||16);$('ux2Grid').addEventListener('change',e=>dispatchValue('gridCount',e.target.value,'change'));$('ux2GridOn').addEventListener('change',e=>dispatchChecked('gridOn',e.target.checked));$('ux2Symmetry').value=$('symmetry')?.value||'off';$('ux2Symmetry').addEventListener('change',e=>dispatchValue('symmetry',e.target.value,'change'));$('ux2SymmetryGuides').addEventListener('change',e=>dispatchChecked('symmetryGuides',e.target.checked));$('ux2Guide').value=$('constructionGuide')?.value||'off';$('ux2Guide').addEventListener('change',e=>dispatchValue('constructionGuide',e.target.value,'change'));$('ux2SnapOn').addEventListener('change',e=>dispatchChecked('snapOn',e.target.checked))}"
rep(old_pattern_events,new_pattern_events,'pattern events')
rep("document.querySelectorAll('[data-ux2-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.ux2Tool)));","document.querySelectorAll('[data-ux2-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.ux2Tool)));\n  document.querySelectorAll('[data-ux2-action="image"]').forEach(b=>b.addEventListener('click',()=>clickOld('focusAddImage')||clickOld('files')));",'image action')
p.write_text(s,encoding='utf-8')

css=Path('app/assets/canvas-first-v2.css')
c=css.read_text(encoding='utf-8')
extra='''
.ux2-brush-list{display:grid;gap:7px}.ux2-brush-card{display:grid;grid-template-columns:78px 1fr;gap:10px;align-items:center;text-align:left;border:1px solid #d3dae2;background:#fff;border-radius:11px;padding:9px;color:#253342}.ux2-brush-card.active{background:#e3ebf3;border-color:#b8c8d8}.ux2-brush-card strong{display:block;font-size:12px}.ux2-brush-card small{display:block;color:#71808f;margin-top:2px;font-size:10px}.ux2-brush-sample{height:24px;position:relative}.ux2-brush-sample:after{content:"";position:absolute;left:4px;right:4px;top:50%;height:3px;border-radius:8px;background:#607b9b;transform:translateY(-50%) rotate(-4deg)}.ux2-brush-sample.pencil:after{height:1px;opacity:.7}.ux2-brush-sample.marker:after{height:8px;opacity:.45}.ux2-brush-sample.texture:after{height:6px;background:repeating-linear-gradient(90deg,#607b9b 0 6px,transparent 6px 10px)}.ux2-brush-sample.stamp:after{height:8px;background:radial-gradient(circle,#607b9b 0 3px,transparent 4px);background-size:15px 8px}.ux2-segment{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.ux2-segment button{border:1px solid #ccd4dd;background:#fff;border-radius:9px;padding:8px;font-size:11px;font-weight:700;color:#344556}.ux2-field-label{display:grid;gap:5px;margin:8px 0;color:#586777;font-size:11px;font-weight:750}.ux2-field-label input,.ux2-field-label select{width:100%;border:1px solid #ccd4dd;background:#fff;border-radius:9px;padding:8px;color:#263442}.ux2-check{display:flex;align-items:center;gap:7px;margin:9px 0;font-size:11px;color:#455567}.ux2-check-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:8px}.ux2-check-grid label{display:flex;align-items:center;gap:4px;font-size:10px;color:#556473}.ux2-info{font-size:11px;line-height:1.45;color:#647281;margin:9px 0 0}
'''
if '.ux2-brush-list{' not in c:c+=extra
css.write_text(c,encoding='utf-8')
print('Deepened canvas-first tool discoverability and exposed existing advanced controls')
